services:
  - type: web
    name: IronTONBot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TON_WALLET
        sync: false
      - key: LOG_CHAT_ID
        sync: false
